services:
  - type: web
    name: myproject-frontend
    env: node
    rootDir: frontend
    buildCommand: npm run build
    startCommand: npm start
    staticPublishPath: .next
    envVars:
      - key: NODE_ENV
        value: production
        
  - type: web
    name: myproject-backend
    env: node
    rootDir: backend
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
